### ISSUE TITLE
Option -fcompound-names not fully functional possibly.

### ISSUE THREAD

**Issue by jmcarter9t** [vlm/asn1c#211] opened 2017-10-03 22:20 UTC
Compiling sae j2735 MessageFrame AND ieee 1609.2 and using -fcompound-names to prevent name overlap.  TwoDLocation.h is generated and it includes Latitude.h ; however, because of compound-names Latitude.h should be called DSRC_Latitude.h.  This name is not being propagated throughout.  Attached is a screenshoot of another issue that popped up after manually fixing the above. Here it appears the name should be asn_DEF_DSRC_Latitude but has been written as asn_DEF_Latitude

Thanks!

<img width="1388" alt="screen shot 2017-10-03 at 6 18 44 pm" src="https://user-images.githubusercontent.com/1124162/31151822-5589288c-a867-11e7-8985-46270f75795c.png">

<img width="1058" alt="screen shot 2017-10-03 at 5 53 44 pm" src="https://user-images.githubusercontent.com/1124162/31151265-a560c520-a864-11e7-8f5c-e505ff8e3535.png">

**Comment by vlm** [comment] 2017-10-04 01:55
Please attach complete logs in a text format. The logs should show the commands you typed in to compile both specs.

**Comment by brchiu** [comment] 2017-10-04 05:50
hi @vlm, 

I found it can be reproduced by processing `1609-2.2016.asn1` and `J2735_201603.asn1` simultaneously. 
```
../../asn1c/asn1c -S ../../skeletons -pdu=MessageFrame -fcompound-names -gen-PER -pdu=all ../IEEE-1609.2-2016.asn1 ../J2735_201603.asn1
```

**Comment by brchiu** [comment] 2017-10-04 06:08
A minimum example ASN.1 to reproduce this problem.

Looks like function `asn1f_check_duplicate()` is incapable to detect this kind of duplication.
```
ModuleA 
DEFINITIONS AUTOMATIC TAGS::= BEGIN

Latitude ::= INTEGER(-180..180)
LocationData ::= SEQUENCE {
    lat      Latitude
}
END

ModuleB
DEFINITIONS AUTOMATIC TAGS ::= BEGIN

NinetyInt ::= INTEGER (-90..90)

Latitude ::= NinetyInt
Location ::= SEQUENCE  {
    latitude      Latitude
}
END
```
If `Latitude` in `ModuleB` does not referenced to other type, it will successfully detect it.
```
Latitude ::= INTEGER (-90..90)
```

**Comment by brchiu** [comment] 2017-10-04 12:17
The reason that if `Latitude` in `ModuleB` refers to other type then there are only 

```
#include "Latitude.h" 
/* Location */
typedef struct Location {
	Latitude_t	 latitude;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Location_t;
```
instead of expected prefixed version : 
```
#include "ModuleB_Latitude.h" 
/* Location */
typedef struct Location {
	ModuleB_Latitude_t	 latitude;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Location_t;
```
Inside function `asn1c_type_name()` , if `expr->expr_type` is `A1TC_REFERENCE`, then the terminal type, i.e. `NinetyInt` will be retrieved by `asn1f_find_terminal_type_ex()` . However, `NinetyInt` does not clash with other name so `exprid = terminal;` will not be executed.

In this specific scenario, actually we only need to resolve `latitude` to `Latitude` for finding name clash.

Looks like @vlm is working on re-writing a new name construction mechanism, instead of using current `asn1c_type_name()` and `asn1c_make_identifier()` functions. 

So I tentatively leave this issue for a while.

**Comment by jmcarter9t** [comment] 2017-10-04 14:29
I will attach the -Wdebug-compiler output, but didn't see any other type of logging -- if there is a specific method to produce logs, please let me know and I will forward those.

Here is the command I ran: ```asn1c -Wdebug-compiler -fcompound-names -gen-PER -pdu=all 1609dot2-base-types.asn 1609dot2-schema.asn J2735_201603DA.ASN```

[output.log](https://github.com/vlm/asn1c/files/1356129/output.log)

Thank you for the help!

Jason

**Comment by vlm** [comment] 2017-10-05 09:07
I am not changing this code anymore that can materially affect this issue. I'd appreciate if someone could help with this issue.

**Comment by vlm** [comment] 2017-10-09 02:55
Merged, thanks!

**Closed by vlm** 2017-10-09 02:55 UTC
